run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
  skip-files:
    - ".*_test.go"
    - ".*/generated/.*"

linters-settings:
  lll:
    line-length: 120

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell

issues:
  exclude-use-default: false
