---
services:
  mysql-test:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: jahlo
      MYSQL_DATABASE: alex
    ports:
      - "3307:3306"
    volumes:
      - ./testdata/mysql:/docker-entrypoint-initdb.d
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-pjahlo",
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  neo4j-test:
    image: neo4j:4.4
    environment:
      NEO4J_AUTH: neo4j/testpass
      NEO4J_dbms_memory_pagecache_size: 1G
      NEO4J_dbms_memory_heap_initial__size: 1G
      NEO4J_dbms_memory_heap_max__size: 1G
      NEO4J_dbms_security_http_access_control_allow_origin: "*"
    ports:
      - "7687:7687" # Bolt
      - "7474:7474" # HTTP
    volumes:
      - ./testdata/neo4j/import:/import
    healthcheck:
      test:
        ["CMD", "cypher-shell", "-u", "neo4j", "-p", "testpass", "RETURN 1;"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      mysql-test:
        condition: service_healthy
      neo4j-test:
        condition: service_healthy
    environment:
      MYSQL_HOST: mysql-test
      MYSQL_PORT: 3306 # Toto je interní port v Docker síti
      MYSQL_USER: root
      MYSQL_PASSWORD: jahlo
      MYSQL_DATABASE: alex
      NEO4J_URI: bolt://neo4j-test:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: testpass
    volumes:
      - .:/go/src/mysql-graph-visualizer
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: "no"

