---
- name: Set up local development environment with Neo4j, Golang, and Neo4j-MySQL bridge
  hosts: localhost
  become: true
  tasks:
    - name: Ensure Docker is installed
      package:
        name: docker
        state: present

    - name: Ensure Docker Compose is installed
      package:
        name: docker-compose
        state: present

    - name: Pull Neo4j Docker image
      docker_image:
        name: neo4j
        tag: latest
        source: pull

    - name: Create a network for the applications
      docker_network:
        name: neo4jbridge_network
        driver: bridge

    - name: Run Neo4j container
      docker_container:
        name: neo4j
        image: neo4j
        state: started
        restart_policy: always
        ports:
          - "7474:7474" # Neo4j browser
          - "7687:7687" # Bolt protocol
        networks:
          - name: neo4jbridge_network
        env:
          - NEO4J_AUTH=neo4j/test # Set authentication values

    - name: Pull MySQL Docker image
      docker_image:
        name: mysql
        tag: latest
        source: pull

    - name: Run MySQL container
      docker_container:
        name: mysql
        image: mysql
        state: started
        restart_policy: always
        ports:
          - "3306:3306"
        networks:
          - name: neo4jbridge_network
        env:
          - MYSQL_ROOT_PASSWORD=root

    - name: Set up Go environment (assumes Go is installed on host)
      shell: |
        cd /srv/http/go &&
        go mod init alex-visualizer &&
        go get -u github.com/neo4j/neo4j-go-driver/v4

    - name: Clone or update Neo4j-MySQL bridge repository
      git:
        repo: "git@github.com:peter7775/alex-visualizer.git"
        dest: /srv/http/go/alex-visualizer

    - name: Build Neo4j-MySQL bridge (assumes Dockerfile is present)
      docker_image:
        name: alex-visualizer
        build:
          path: /srv/http/go/alex-visualizer

    - name: Run Neo4j-MySQL bridge container
      docker_container:
        name: alex-visualizer
        image: alex-visualizer
        state: started
        restart_policy: always
        ports:
          - "8080:8080" # Example port
        networks:
          - name: neo4jbridge_network
