name: Bug Report
description: File a bug report to help us improve the project
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: checkboxes
    id: terms
    attributes:
      label: Prerequisites
      description: By submitting this issue, you agree to follow our Code of Conduct and confirm you've checked the following
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have checked the project documentation
          required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of mysql-graph-visualizer are you running?
      placeholder: e.g., v1.0.0, latest commit hash, or main branch
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Start the application with '...'
        2. Configure MySQL connection with '...'
        3. Run transformation with '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: Describe what should happen...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happens
      placeholder: Describe what actually happens...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide your environment details
      value: |
        - OS: 
        - Go Version: 
        - MySQL Version: 
        - Neo4j Version: 
        - Docker (if used): 
      render: markdown
    validations:
      required: true

  - type: textarea
    id: configuration
    attributes:
      label: Configuration
      description: Please share relevant parts of your config.yml (remove sensitive data)
      render: yaml
      placeholder: |
        mysql:
          host: localhost
          port: 3306
          # ... other config

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: If applicable, add relevant log output
      render: text
      placeholder: Paste relevant log output here...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here, such as screenshots or related issues
